services:
  - type: web
    name: plastic-world
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: plastic-world-db
    plan: free
